<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2010-9
</py:def>

<py:def function="announcement_date">
2010-12-07
</py:def>

<py:def function="announcement_summary">
Unvalidated input on error page.
</py:def>

<py:def function="announcement_description">
It was possible to display arbitrary text and link to external site using
parameters passed to particular script.
</py:def>

<py:def function="announcement_severity">
This issue is considered minor, because the only purpose of affected file is to
display an error message.
</py:def>

<py:def function="announcement_affected">
All versions prior to 3.4.0-beta1.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 3.4.0-beta1 or newer or apply patch listed below.
</py:def>

<!--! Links to reporter etc, do not forget to escape & to &amp; -->
<py:def function="announcement_references">
This issue was reported by <a
href="http://www.exploit-db.com/exploits/15699/">Tiger Security Team</a>.
</py:def>

<!--! CVE ID of the report, this is automatically added to references -->
<py:def function="announcement_cve">CVE-2010-4480</py:def>

<py:def function="announcement_cwe">661 20</py:def>

<py:def function="announcement_commits">
aa6fec0532a9dd48d4e35831c1b1c9785c124dd7
</py:def>

<py:def function="announcement_commits_3_3">
9ebd401b0ea4efea8ddc8cd846da559bf420ccaa
</py:def>

<py:def function="announcement_commits_2_11">
b01a58118f973f98ab99a4bb28d340af49fa251f
</py:def>

<xi:include href="_page.tpl" />
</html>
