<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2010-6
</py:def>

<py:def function="announcement_date">
2010-08-30
</py:def>

<py:def function="announcement_summary">
XSS attack using debugging messages.
</py:def>

<py:def function="announcement_description">
It was possible to conduct a XSS attack using error messages in PHP backtrace.
</py:def>

<py:def function="announcement_mitigation">
Additional steps from administrator are required to actually exploit this
issue (phpMyAdmin error reporting and collection needs to be enabled, what 
is against recommendation for production setup).
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be non critical.
</py:def>

<py:def function="announcement_affected">
For 3.x: versions before 3.3.6 are affected.
</py:def>

<py:def function="announcement_unaffected">
Branch 2.11.x is not affected by this.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 3.3.6 or newer or apply patch listed below.
</py:def>

<py:def function="announcement_references">
Thanks to Aung Khant from <a href="http://yehg.net">YGN Ethical Hacker Group,
Myanmar</a> for reporting this issue.
</py:def>

<py:def function="announcement_cve">CVE-2010-3056</py:def>

<py:def function="announcement_commits">
133a77fac7d31a38703db2099a90c1b49de62e37
</py:def>

<xi:include href="_page.tpl" />
</html>
