<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2012-2
</py:def>

<py:def function="announcement_date">
2012-03-28
</py:def>

<py:def function="announcement_summary">
Path disclosure due to missing verification of file presence.
</py:def>

<py:def function="announcement_description">
The show_config_errors.php scripts did not validate the presence of the
configuration file, so an error message shows the full path of this file,
leading to possible further attacks.
</py:def>

<py:def function="announcement_mitigation">
For the error messages to be displayed, php.ini's error_reporting must be set 
to E_ALL and display_errors must be On (these settings are not recommended 
on a production server in the PHP manual).
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be non critical.
</py:def>

<py:def function="announcement_affected">
Versions 3.4.x are affected.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 3.4.10.2 or newer or apply the related patch listed below.
</py:def>

<py:def function="announcement_references">
Thanks to Mateusz Goik from <a href="http://www.aliantsoft.pl">AliantSoft</a> for reporting this issue.
</py:def>

<py:def function="announcement_cve">CVE-2012-1902</py:def>

<py:def function="announcement_cwe">20 200</py:def>

<py:def function="announcement_commits">
c51817d3b8cb05ff54dca9373c0667e29b8498d4
</py:def>

<xi:include href="_page.tpl" />
</html>
